# Generated by Django 3.1.1 on 2020-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name_plural': 'Cake',
            },
        ),
    ]
