# Generated by Django 3.1.1 on 2020-09-20 11:51

import applications.index.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('prices', models.TextField(blank=True, null=True, verbose_name='Стоимость и заказ')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(storage=applications.index.storages.OverwriteStorage(), upload_to='images/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=130, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Название десерта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.cake', verbose_name='Десерт')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Cake_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название десерта')),
                ('ingredients', models.TextField(max_length=300, verbose_name='Описание ингредиентов')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.cake', verbose_name='Десерт')),
            ],
            options={
                'verbose_name': 'Подвид десерта',
                'verbose_name_plural': 'Подвиды десертов',
            },
        ),
    ]
