# Generated by Django 3.1.1 on 2020-09-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
        migrations.RemoveField(
            model_name='cake',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Название десерта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cake', verbose_name='Десерт')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Cake_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название десерта')),
                ('ingredients', models.CharField(max_length=100, verbose_name='Описание ингредиентов')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cake', verbose_name='Десерт')),
            ],
            options={
                'verbose_name': 'Подвид десерта',
                'verbose_name_plural': 'Подвиды десертов',
            },
        ),
    ]
