# Generated by Django 3.1.1 on 2020-09-18 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200904_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='url',
            field=models.SlugField(default=datetime.datetime(2020, 9, 18, 16, 8, 16, 70583, tzinfo=utc), max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
