# Generated by Django 3.1.1 on 2020-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('phone', models.CharField(default='', max_length=150, verbose_name='Телефон')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Почта')),
                ('vk', models.CharField(default='', max_length=150, verbose_name='ВК')),
                ('instagram', models.CharField(default='', max_length=150, verbose_name='Инстаграм')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
