# Generated by Django 3.1.1 on 2020-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='vk',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
        ),
    ]
