# Generated by Django 3.1.1 on 2020-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200920_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(default='', max_length=150, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='vk',
            field=models.CharField(default='', max_length=150, verbose_name='ВК'),
        ),
    ]
