# Generated by Django 3.1.1 on 2020-09-21 15:34

import applications.index.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutInfoOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название опции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание опции')),
            ],
            options={
                'verbose_name': 'опции оплаты и доставки',
                'verbose_name_plural': 'опции оплаты доставки',
            },
        ),
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(storage=applications.index.storages.OverwriteStorage(), upload_to='.', verbose_name='Изображение')),
                ('options', models.ManyToManyField(to='checkout.CheckoutInfoOption')),
            ],
            options={
                'verbose_name': 'информация об оплате и доставке',
                'verbose_name_plural': 'информация об оплате и доставке',
            },
        ),
    ]
